#PELT I18N (Internationalization)
#Created December 4, 2013 at 15:30

import settings
import os.path, pickle, re

def setlang(lang):
	global msgs
	langdir = os.path.join(settings.langdir, lang)
	msgs = {}
	for l in os.listdir(langdir):
		langfile = os.path.join(langdir, l)
		ignore = ["Icon\n", "desktop.ini", ".DS_Store", ".dropbox.attr"] #This array prevents invisible files generated by Google Drive, Dropbox, or Macs from causing problems
		e = False
		for f in ignore:
			if f in l:
				e = True
				break
		
		if not e:
			with open(langfile, 'rb') as handle: msgs.update(pickle.load(handle))
	settings.lang = lang

def language():
	wait=True
	wait2=True
	while wait:
		while wait2:
			choice = getInput.choice('Language/Idioma', ['English','Espanol (Archivo del Idioma no Esta Presente)','Francais (Fichier de Langue pas present)', 'Quit'])
			if choice == 'English':
				setlang("en")
				wait2 = False
			elif choice == '': quit('', nosave=True)
			else: output("Invalid option/Opcion incorrecto/L'option invalide", dict=False)
		else: output("Language File Version Incompatible/Version del Archivo del Idioma Incompatible/Version de L'archive du Language Incompatible", dict=False)
	
def m(key, r=0, modifier='normal', color=False):
	global msgs
	if r == 1: print "You should fix this message, it has m('"+key+"', r=1).  Remove the r=1"
	msg = msgs[key]
	if not color: re.sub(msg, "\[[^\]]\]", "")
	return msg
	#if modifier == 'caps': msg = msgs[key].upper()
	#elif modifier == 'title': msg = msgs[key].title()
	#elif modifier == 'lower': msg = msgs[key].lower()
	#return msg

setlang('en')